### ISSUE TITLE
Does not build with OpenCV 4

### ISSUE THREAD

**Issue by ChristophHaag** [OSVR/OSVR-Core#596]
Archlinux ships OpenCV 4 and osvr-core does not build with it.

There are several \#ifdefs in the code checking explicitly for OpenCV 2 or 3 and producing an \#error for OpenCV 4 but just removing those does not help, apparently the API changed.

osvr-core should either

1) build an appropriate opencv version with osvr-core
2) allow the selection of an opencv installation in a non default path (/opt/...) in cmake
3) update to the opencv 4 API

**Comment by rpavlik** [comment]
Can you set OpenCV_DIR in CMake? That should let you choose the location of
the CMake config file to use. (You could also disable building with opencv
if you don't need the hdk optical tracker.)

In any case, I will have to look and see what they broke in the API ;)
thanks for the report!

**Comment by ChristophHaag** [comment]
Updated to make it compile with OpenCV4: https://github.com/ChristophHaag/OSVR-Core/commit/f693399b1d7cb28b34c767c8aa78c4ec6c1a7ce3

I have not tested running this, I mostly just used the suggestions from my IDE. I haven't cared to test whether the code still works with OpenCV3, personally I would just ditch OpenCV2 and OpencV3 support to minimize the maintenance burden.

**Comment by rpavlik** [comment]
awesome thanks christoph, I will check and merge this soonish.

**Comment by isopix** [comment]
[(https://aur.archlinux.org/packages/osvr-core-git/)]
it's patched version for OpenCV4. It compiled with OpenCV 4.3 and older gcc. But it won't compile with OpenCV 4.5

[`85%] Built target com_osvr_Multiserver Scanning dependencies of target vbtracker-core [ 85%] Building CXX object plugins/videobasedtracker/CMakeFiles/vbtracker-core.dir/BeaconBasedPoseEstimator.cpp.o /mnt/magazyn/archlinux/aur-osvr-core-git/src/osvr-core/plugins/videobasedtracker/BeaconBasedPoseEstimator.cpp: In member function ‘bool osvr::vbtracker::BeaconBasedPoseEstimator::m_pnpransacEstimator(osvr::vbtracker::LedGroup&)’: /mnt/magazyn/archlinux/aur-osvr-core-git/src/osvr-core/plugins/videobasedtracker/BeaconBasedPoseEstimator.cpp:303:14: error: ‘void ransacResult’ has incomplete type 303 | auto ransacResult = cv::solvePnPRansac( | ^~~~~~~~~~~~ make[2]: [plugins/videobasedtracker/CMakeFiles/vbtracker-core.dir/build.make:82: plugins/videobasedtracker/CMakeFiles/vbtracker-core.dir/BeaconBasedPoseEstimator.cpp.o] Error 1 make[1]: [CMakeFiles/Makefile2:2083: plugins/videobasedtracker/CMakeFiles/vbtracker-core.dir/all] Error 2 make: *** [Makefile:171: all] Error `
