### ISSUE TITLE
Missing OpenCV include path (noticed with OpenCV 3.0.0rc1)

### ISSUE THREAD

**Issue by janoc** [OSVR/OSVR-Core#138]
The build fails with the following error in multiple places:

2>------ Build started: Project: osvrCommon, Configuration: RelWithDebInfo x64 ------
2>  ImagingComponent.cpp
2>C:\R\Projects\0Sandbox\osvr\windows\OSVR-Core\inc\osvr/Util/OpenCVTypeDispatch.h(34): fatal error C1083: Cannot open include file: 'opencv2/core/types_c.h': No such file or directory

The path for the OpenCV header files is not set in the MSVC project, despite OpenCV being found correctly by CMake. OpenCV still uses the OpenCV_INCLUDE_DIRS, OpenCV_LIBS and OpenCV_LIB_DIR variables instead of the newer target properties.

**Comment by janoc** [comment]
**Additional information**

The problem with the include path can be worked around by adding: 
`include_directories(${OpenCV_INCLUDE_DIRS}) `

However, in that case the compilation fails with many syntax errors, it seems that there is some issue with the header files being included - either a file that isn't meant to be included directly is or the headers are being included in an incorrect order, leading to some macros being undefined.

The above is, in fact a regression with OpenCV 3.0.0rc1, OSVR builds fine with the older 2.4.11.

**Comment by rpavlik** [comment]
OK, I've got a fix committed and ready to push regarding the include paths, but that won't fix the OpenCV 3 compatibility. Will open a separate ticket for that.

**Comment by rpavlik** [comment]
Fix pushed.
