### ISSUE TITLE
Ubuntu 15.10 cmake error

### ISSUE THREAD

**Issue by plc66** [OSVR/OSVR-Core#351]
Probably already already sorted, found similar with a Mac user. 

Using non-windows-woraround branch, used to compile fine with Ubuntu 15.04 (libboost 1.55), now with Ubuntu 15.10 (installed libboost 1.60, as 1.58 reported buggy).
   
Cannot cmake osvr-core : 

`CMake Error at cmake-local/BoostTargets.cmake:22 (message):
  Using an untested Boost version - inspect the Boost Interprocess release
  notes/changelog/diffs to see if any ABI breaks affect us.
Call Stack (most recent call first):
  CMakeLists.txt:289 (include)
`
Help pretty please ?

**Comment by plc66** [comment]
OK got a bit further. 

In the non-windows-workaround branch, edited ./OSVR-Core/cmake-local/BoostTarget.cmake , line 21 to:
 `if(Boost_VERSION GREATER 106000)`

cmake does not complain.

Run make, compile fails at 75% : 
`[ 75%] Building CXX object src/osvr/Common/CMakeFiles/osvrCommon.dir/IPCRingBuffer.cpp.o
/home/pilou/OSVR/OSVR-core/OSVR-Core/src/osvr/Common/IPCRingBuffer.cpp:55:2: error: #error "Using an untested Boost version - inspect the Boost Interprocess release notes/changelog to see if any ABI breaks affect `us."`

Edit ./OSVR-Core/src/osvr/Common/IPCRingBuffer.cpp, line 55 : 
`#if (BOOST_VERSION > 106000)`

Just tested OpenGLSample, seems to work without issues... 

Will post again if I stumble upon more issues with boost 1.60.

**Comment by rpavlik** [comment]
Sorry, this is fixed in the master branch but I didn't update the workaround branch with it apparently.  For what it's worth, people aren't having the trouble with 1.58 that was originally expected/reported, we may have merged a workaround but not a documentation update.
