### ISSUE TITLE
boost::fusion-related compile issue

### ISSUE THREAD

**Issue by rpavlik** [OSVR/OSVR-Core#177]
After merging the EyeTracker branch, we started getting a build error with Boost 1.49.0 as included with Debian Wheezy. Specifically, here's what we observed:

64d97d4ef58a0faf0d3ac3899c7c032dfb875d17 - builds fine with 1.49 (wheezy), 1.55 (jessie), and 1.57 (windows and android)
1b535b21bc68e247ec38ac7327460ac7e808dc79 - Builds fine with 1.55 (jessie), and 1.57 (windows and android), but does not build properly with 1.49 (wheezy)

The following commits up through and including d5b68a9c8f0b70416637f5b610ea114479b36c68 were (increasingly desperate) attempts to work around the issue. Some might have been useful, but none fixed the builds. The result of building that last revision include this log:

```
[ 28%] Building CXX object src/osvr/Common/CMakeFiles/osvrCommon.dir/ClientContext.cpp.o
In file included from /var/lib/jenkins/jobs/OSVR-Core-Build-Linux-Matrix/workspace/COMPILER/clang/label/Linux/src/osvr/Common/ClientContext.cpp:27:
In file included from /var/lib/jenkins/jobs/OSVR-Core-Build-Linux-Matrix/workspace/COMPILER/clang/label/Linux/inc/osvr/Common/ClientInterface.h:32:
In file included from /var/lib/jenkins/jobs/OSVR-Core-Build-Linux-Matrix/workspace/COMPILER/clang/label/Linux/inc/osvr/Common/InterfaceState.h:29:
In file included from /var/lib/jenkins/jobs/OSVR-Core-Build-Linux-Matrix/workspace/COMPILER/clang/label/Linux/inc/osvr/Common/ReportMap.h:39:
In file included from /usr/include/boost/fusion/include/map.hpp:10:
In file included from /usr/include/boost/fusion/container/map.hpp:13:
/usr/include/boost/fusion/container/map/convert.hpp:24:30: error: implicit instantiation of undefined template 'boost::fusion::detail::as_map<11>'
            typedef typename gen::
                             ^
/var/lib/jenkins/jobs/OSVR-Core-Build-Linux-Matrix/workspace/COMPILER/clang/label/Linux/inc/osvr/Common/ReportMap.h:69:52: note: in instantiation of template class 'boost::fusion::result_of::as_map<boost::mpl::v_item<boost::fusion::pair<OSVR_EyeTrackerBlinkReport, boost::optional<osvr::common::StateMapContents<OSVR_EyeTrackerBlinkReport> > >, boost::mpl::v_item<boost::fusion::pair<OSVR_EyeTracker3DReport, boost::optional<osvr::common::StateMapContents<OSVR_EyeTracker3DReport> > >, boost::mpl::v_item<boost::fusion::pair<OSVR_EyeTracker2DReport, boost::optional<osvr::common::StateMapContents<OSVR_EyeTracker2DReport> > >, boost::mpl::v_item<boost::fusion::pair<OSVR_DirectionReport, boost::optional<osvr::common::StateMapContents<OSVR_DirectionReport> > >, boost::mpl::v_item<boost::fusion::pair<OSVR_Location2DReport, boost::optional<osvr::common::StateMapContents<OSVR_Location2DReport> > >, boost::mpl::v_item<boost::fusion::pair<OSVR_ImagingReport, boost::optional<osvr::common::StateMapContents<OSVR_ImagingReport> > >, boost::mpl::v_item<boost::fusion::pair<OSVR_OrientationReport, boost::optional<osvr::common::StateMapContents<OSVR_OrientationReport> > >, boost::mpl::v_item<boost::fusion::pair<OSVR_PositionReport, boost::optional<osvr::common::StateMapContents<OSVR_PositionReport> > >, boost::mpl::v_item<boost::fusion::pair<OSVR_PoseReport, boost::optional<osvr::common::StateMapContents<OSVR_PoseReport> > >, boost::mpl::v_item<boost::fusion::pair<OSVR_ButtonReport, boost::optional<osvr::common::StateMapContents<OSVR_ButtonReport> > >, boost::mpl::v_item<boost::fusion::pair<OSVR_AnalogReport, boost::optional<osvr::common::StateMapContents<OSVR_AnalogReport> > >, boost::mpl::vector0<mpl_::na>, 0>, 0>, 0>, 0>, 0>, 0>, 0>, 0>, 0>, 0>, 0> >' requested here
                typename boost::fusion::result_of::as_map<PairSequence>::type
                                                   ^
/var/lib/jenkins/jobs/OSVR-Core-Build-Linux-Matrix/workspace/COMPILER/clang/label/Linux/inc/osvr/Common/InterfaceState.h:61:21: note: in instantiation of template class 'osvr::common::traits::GenerateReportMap<osvr::common::StateMapValueType<mpl_::arg<1> > >' requested here
    typedef traits::GenerateReportMap<StateMapValueType<boost::mpl::_1> >::type
                    ^
/usr/include/boost/fusion/container/map/detail/as_map.hpp:26:12: note: template is declared here
    struct as_map;
           ^
In file included from /var/lib/jenkins/jobs/OSVR-Core-Build-Linux-Matrix/workspace/COMPILER/clang/label/Linux/src/osvr/Common/ClientContext.cpp:27:
In file included from /var/lib/jenkins/jobs/OSVR-Core-Build-Linux-Matrix/workspace/COMPILER/clang/label/Linux/inc/osvr/Common/ClientInterface.h:32:
In file included from /var/lib/jenkins/jobs/OSVR-Core-Build-Linux-Matrix/workspace/COMPILER/clang/label/Linux/inc/osvr/Common/InterfaceState.h:29:
In file included from /var/lib/jenkins/jobs/OSVR-Core-Build-Linux-Matrix/workspace/COMPILER/clang/label/Linux/inc/osvr/Common/ReportMap.h:39:
In file included from /usr/include/boost/fusion/include/map.hpp:10:
In file included from /usr/include/boost/fusion/container/map.hpp:13:
/usr/include/boost/fusion/container/map/convert.hpp:25:26: error: 'apply' following the 'template' keyword does not refer to a template
                template apply<typename result_of::begin<Sequence>::type>::type
                         ^~~~~
/usr/include/boost/fusion/container/map/convert.hpp:24:30: error: implicit instantiation of undefined template 'boost::fusion::detail::as_map<11>'
            typedef typename gen::
                             ^
/var/lib/jenkins/jobs/OSVR-Core-Build-Linux-Matrix/workspace/COMPILER/clang/label/Linux/inc/osvr/Common/ReportMap.h:69:52: note: in instantiation of template class 'boost::fusion::result_of::as_map<boost::mpl::v_item<boost::fusion::pair<OSVR_EyeTrackerBlinkReport, std::vector<std::function<void (const OSVR_TimeValue *, const OSVR_EyeTrackerBlinkReport *)>, std::allocator<std::function<void (const OSVR_TimeValue *, const OSVR_EyeTrackerBlinkReport *)> > > >, boost::mpl::v_item<boost::fusion::pair<OSVR_EyeTracker3DReport, std::vector<std::function<void (const OSVR_TimeValue *, const OSVR_EyeTracker3DReport *)>, std::allocator<std::function<void (const OSVR_TimeValue *, const OSVR_EyeTracker3DReport *)> > > >, boost::mpl::v_item<boost::fusion::pair<OSVR_EyeTracker2DReport, std::vector<std::function<void (const OSVR_TimeValue *, const OSVR_EyeTracker2DReport *)>, std::allocator<std::function<void (const OSVR_TimeValue *, const OSVR_EyeTracker2DReport *)> > > >, boost::mpl::v_item<boost::fusion::pair<OSVR_DirectionReport, std::vector<std::function<void (const OSVR_TimeValue *, const OSVR_DirectionReport *)>, std::allocator<std::function<void (const OSVR_TimeValue *, const OSVR_DirectionReport *)> > > >, boost::mpl::v_item<boost::fusion::pair<OSVR_Location2DReport, std::vector<std::function<void (const OSVR_TimeValue *, const OSVR_Location2DReport *)>, std::allocator<std::function<void (const OSVR_TimeValue *, const OSVR_Location2DReport *)> > > >, boost::mpl::v_item<boost::fusion::pair<OSVR_ImagingReport, std::vector<std::function<void (const OSVR_TimeValue *, const OSVR_ImagingReport *)>, std::allocator<std::function<void (const OSVR_TimeValue *, const OSVR_ImagingReport *)> > > >, boost::mpl::v_item<boost::fusion::pair<OSVR_OrientationReport, std::vector<std::function<void (const OSVR_TimeValue *, const OSVR_OrientationReport *)>, std::allocator<std::function<void (const OSVR_TimeValue *, const OSVR_OrientationReport *)> > > >, boost::mpl::v_item<boost::fusion::pair<OSVR_PositionReport, std::vector<std::function<void (const OSVR_TimeValue *, const OSVR_PositionReport *)>, std::allocator<std::function<void (const OSVR_TimeValue *, const OSVR_PositionReport *)> > > >, boost::mpl::v_item<boost::fusion::pair<OSVR_PoseReport, std::vector<std::function<void (const OSVR_TimeValue *, const OSVR_PoseReport *)>, std::allocator<std::function<void (const OSVR_TimeValue *, const OSVR_PoseReport *)> > > >, boost::mpl::v_item<boost::fusion::pair<OSVR_ButtonReport, std::vector<std::function<void (const OSVR_TimeValue *, const OSVR_ButtonReport *)>, std::allocator<std::function<void (const OSVR_TimeValue *, const OSVR_ButtonReport *)> > > >, boost::mpl::v_item<boost::fusion::pair<OSVR_AnalogReport, std::vector<std::function<void (const OSVR_TimeValue *, const OSVR_AnalogReport *)>, std::allocator<std::function<void (const OSVR_TimeValue *, const OSVR_AnalogReport *)> > > >, boost::mpl::vector0<mpl_::na>, 0>, 0>, 0>, 0>, 0>, 0>, 0>, 0>, 0>, 0>, 0> >' requested here
                typename boost::fusion::result_of::as_map<PairSequence>::type
                                                   ^
/var/lib/jenkins/jobs/OSVR-Core-Build-Linux-Matrix/workspace/COMPILER/clang/label/Linux/inc/osvr/Common/InterfaceCallbacks.h:53:21: note: in instantiation of template class 'osvr::common::traits::GenerateReportMap<osvr::common::CallbackStorageType<mpl_::arg<-1> > >' requested here
    typedef traits::GenerateReportMap<CallbackStorageType<boost::mpl::_> >::type
                    ^
/usr/include/boost/fusion/container/map/detail/as_map.hpp:26:12: note: template is declared here
    struct as_map;
           ^
In file included from /var/lib/jenkins/jobs/OSVR-Core-Build-Linux-Matrix/workspace/COMPILER/clang/label/Linux/src/osvr/Common/ClientContext.cpp:27:
In file included from /var/lib/jenkins/jobs/OSVR-Core-Build-Linux-Matrix/workspace/COMPILER/clang/label/Linux/inc/osvr/Common/ClientInterface.h:32:
In file included from /var/lib/jenkins/jobs/OSVR-Core-Build-Linux-Matrix/workspace/COMPILER/clang/label/Linux/inc/osvr/Common/InterfaceState.h:29:
In file included from /var/lib/jenkins/jobs/OSVR-Core-Build-Linux-Matrix/workspace/COMPILER/clang/label/Linux/inc/osvr/Common/ReportMap.h:39:
In file included from /usr/include/boost/fusion/include/map.hpp:10:
In file included from /usr/include/boost/fusion/container/map.hpp:13:
/usr/include/boost/fusion/container/map/convert.hpp:25:26: error: 'apply' following the 'template' keyword does not refer to a template
                template apply<typename result_of::begin<Sequence>::type>::type
                         ^~~~~
4 errors generated.
make[2]: *** [src/osvr/Common/CMakeFiles/osvrCommon.dir/ClientContext.cpp.o] Error 1
make[1]: *** [src/osvr/Common/CMakeFiles/osvrCommon.dir/all] Error 2
make: *** [all] Error 2
```

I don't think there were any confounds like compiler change (esp. since this happens both with the stock GCC and the clang apt repo), but no guarantees.

So, decision: we must either
- Figure out what the issue is and fix it, or
- Increase the minimum required Boost version to something in the range (1.49, 1.55] that doesn't exhibit the bug.

**Comment by godbyk** [comment]
I checked the release notes for Boost 1.50 through 1.55 and the only mention of fusion pointed to this bug fix that was released in 1.55: https://svn.boost.org/trac/boost/ticket/8759

**Comment by rpavlik** [comment]
These were the total changes between 1.49 and 1.55: https://github.com/boostorg/fusion/compare/boost-1.49.0...boost-1.55.0

**Comment by rpavlik** [comment]
Probably fixed by #230
